### ISSUE TITLE
春哥何时可以考虑把rsa签名和验签，至少把验签给加上

### ISSUE THREAD

**Issue by wkii** [openresty/lua-resty-string#26]
对C实在是没有那个功力，希望能有一个rsa签名和验签函数。
基于openssl的签名和验签。这样做一个接口，就可以把验签这块儿的工作交给lua来做了。

**Comment by agentzh** [comment]
@wkii Please, no Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

Regarding your question, yes, maybe at some point. I'm not sure at this point.
