### ISSUE TITLE
calling directive set_decode_hex failed with code -1

### ISSUE THREAD

**Issue by eqkou** [openresty/lua-resty-string#40]
`  decoded = ndk.set_var.set_decode_hex(encoded);`

it works when `encoded` is correct, but if I pass something like `NotACorrectEncodedString` as `encoded` to nginx, it will fail and say `calling directive set_decode_hex failed with code -1` return a 500 code

I wan to suppress the error message, handle the exception myself, something like 

```
decoded = ndk.set_var.set_decode_hex(encoded);
if decoded.failed then
--....
```

How can I do that?

**Comment by agentzh** [comment]
@eqkou I think you can use Lua's standard function `pcall` or `xpcall` to catch the exception on the Lua land?

**Comment by eqkou** [comment]
@agentzh          ` pcall(ndk.set_var.set_decode_hex(encoded)`

the error message still being outputed
