### ISSUE TITLE
Salt size requirement is not reflected in documentation

### ISSUE THREAD

**Issue by bungle** [openresty/lua-resty-string#43]
When this was merged: #42

The documentation was not updated. Examples (using different salt-size than 8) in `README.md` will not work anymore.

**Comment by agentzh** [comment]
@dndx Will you take care of this please? Thanks!

**Comment by agentzh** [comment]
@bungle Will you submit a patch for it? Thanks!

**Comment by dndx** [comment]
@agentzh I will submit a PR to fix this. It was my fault for not updating the doc when fixing the bug.
