### ISSUE TITLE
Using byte arrays for key and iv with AES-128 enc/dec

### ISSUE THREAD

**Issue by slnaing07** [openresty/lua-resty-string#48]
Hello-

I’ve been looking at the lua-resty-string module to do some aes-128 decryption in Lua. 

I have the AES secret key, but it’s not a string- it’s a binary file, and the best I can do is convert it into an array of 16 bytes. I also have the IV, which is an array of 16 bytes of '0'.

I’m looking at the below example from https://github.com/openresty/lua-resty-string:

```
local aes_128_cbc_with_iv = assert(aes:new("1234567890123456",
        nil, aes.cipher(128,"cbc"), {iv="1234567890123456"}))
```
I'm assuming that the first instance of "1234567890123456" is the key, and the second one is the iv.

How should I format the array of bytes that I have for the secret key and the IV into the String formats that will be acceptable for the above example? Is it possible at all, and if so- is there a specific encoding that I have to use to convert those byte arrays to strings?

**Comment by agentzh** [comment]
@slnaing07 Maybe you need this?

https://www.lua.org/manual/5.1/manual.html#pdf-string.char

BTW, Lua strings do support arbitrary binary strings.

**Comment by agentzh** [comment]
BTW, it's also possible to use the `\xFF` hex escaping sequence to construct binary string literals when LuaJIT is used. See

http://luajit.org/extensions.html#lua52
