### ISSUE TITLE
Failed to find function EVP_md5

### ISSUE THREAD

**Issue by smilexcasper** [openresty/lua-resty-string#49]
My Lua code looks like so:

    local aes = require 'aes'
    cipher = aes.encrypt('password', 'secret');
    
When I run it from the command line:

    $ lua unit.lua
    
I get this error message:

> lua: /usr/local/openresty/lualib/resty/aes.lua:106: failed to find function/global EVP_md5 stack traceback: [C]: ? /usr/local/openresty/lualib/resty/aes.lua:106: in main chunk [C]: in function 'require' /usr/local/openresty/nginx/test/unit_tests.lua:4: in main chunk [C]: ?

What is wrong with that and how can I fix it?

**Comment by agentzh** [comment]
@smilexcasper Your openresty links to an openssl library that is too old, maybe. Or you statically link against your OpenSSL library.

I suggest you try our official pre-built binary packages of OpenResty:

https://openresty.org/en/download.html

I'm not sure which OS you are using though.

**Comment by leandromoreira** [comment]
@agentzh I'm trying to use this amazing lib (for testing purposes) without nginx-openresty, is it possible? 

I built a container and when I try to run my tests (busted) that depends on `lua-resty-string` it raises the error `/usr/local/share/lua/5.1/resty/aes.lua:106: /usr/local/bin/luajit: undefined symbol: EVP_md5` which I thought was because my container lacked the  `openssl` lib but even with that lib it still shows the error.

```
FROM ubuntu:14.04.1

# NOTE: This Dockerfile is in the current state only for development purpose!

ENV DEBIAN_FRONTEND noninteractive

# create /app folder and set it as workdir
RUN mkdir /app
WORKDIR /app

# update and upgrade packages
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  curl \
  git \
  libavformat-dev \
  libffi-dev \
  libffi6 \
  libssl-dev \
  luajit \
  unzip \
  python \
  python-dev \
  python-pip \
  libssl-dev \
 && apt-get clean

RUN git clone https://github.com/torch/luajit-rocks.git && \
  cd luajit-rocks && mkdir build && cd build && \
  cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local && make install
RUN git config --global url."https://".insteadOf git://

# it seems there is a bug for luasec https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=724509
RUN luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
RUN luarocks install luasocket
RUN luarocks install busted
RUN luarocks install lua-cassandra
RUN luarocks install luacheck
RUN luarocks install lustache
RUN luarocks install luajson
RUN luarocks install lua-resty-lock
RUN luarocks install lua-resty-string

# add soucecode to /app
WORKDIR /app/lua
```

**Comment by agentzh** [comment]
@leandromoreira Please note the word "resty" in this library's name. Uses of this library outside the OpenResty context is just and will never be supported.

BTW, you may want to check out the `resty` command line utility to run your unit tests directly from the command line:

https://github.com/openresty/resty-cli

**Comment by leandromoreira** [comment]
Thanks @agentzh

**Comment by umarmughal824** [comment]
@leandromoreira I am with you as I am also building the custom one.

**Comment by leandromoreira** [comment]
@umarmughal824 in the end I used a docker image https://github.com/leandromoreira/lua-resty-dynacode/tree/main/usage

**Comment by umarmughal824** [comment]
@leandromoreira I used it with ` --with-http_ssl_module` and it started to fix this but ran into another error that requires you to build openssl with `libssl1.0-dev`.
