### ISSUE TITLE
500 internal error when using test.lua

### ISSUE THREAD

**Issue by c0debreaker** [openresty/lua-resty-string#54]
Hi. I'm very new to lua. What could I be missing? Here is the error I'm getting on my nginx's error.log

```
	no file './resty/sha1.so'
	no file '/usr/local/lib/lua/5.1/resty/sha1.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
```

I searched the whole file sytem but I didn't find them. How do I install it?

**Comment by agentzh** [comment]
@c0debreaker It seems that you screwed up your `lua_package_path` or `package.path` configurations? Your Lua module search paths are definitely messed up.

**Comment by c0debreaker** [comment]
Ok, I'll check it. I just followed the tutorial though I didn't do full absolute path. I used relative path. I'll update it.

**Comment by c0debreaker** [comment]
Ok, I updated it and I am now seeing a new error

2018/02/11 00:40:51 [error] 4936#0: *5 lua entry thread aborted: runtime error: ...resty-quickstart/lua/lua-resty-string/lib/resty/sha1.lua:41: /usr/local/lib/libluajit-5.1.so.2: undefined symbol: SHA1_Init
stack traceback:
coroutine 0:
	[C]: in function '__index'
	...resty-quickstart/lua/lua-resty-string/lib/resty/sha1.lua:41: in function 'new'
	/home/rcamara/repos/openresty-quickstart/./lua/test.lua:3: in function </home/rcamara/repos/openresty-quickstart/./lua/test.lua:1>, client: 127.0.0.1, server: , request: "GET /test HTTP/1.1", host: "localhost:8080"

**Comment by c0debreaker** [comment]
ah, looks like it's similar to this one. I had a feeling this morning that I may have issues since I didn't compile nginx with openssl support - https://github.com/openresty/openresty/issues/20

**Comment by c0debreaker** [comment]
I got it working! :)
```
rcamara@nginx:~/repos$ curl http://localhost:8080/test
sha1: b7e23ec29af22b0b4e41da31e868d57226121c84
md5: 5d41402abc4b2a76b9719d911017c592
true
sha224: ea09ae9cc6768c50fcee903ed054556e5bfc8347907f12598aa24193
true
sha256: 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
true
sha512: 9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca72323c3d99ba5c11d7c7acc6e14b8c5da0c4663475c2e5c3adef46f73bcdec043
true
true
sha384: 59e1748777448c69de6b800d7a33bbfb9ff1b463e44354c3553bcdb9c666fa90125a3c79f90397bdf5f6a13de828684f
pseudo-random: 75914cd39b1188b2910c2d9eb97f97d1
random: 193f56aecdd274634c368062ab73fbc1
AES 128 CBC (MD5) Encrypted HEX: 6d87d6b11c6bf0dcb76d1aa611520b3c
AES 128 CBC (MD5) Decrypted: Secret message!
AES 256 CBC (SHA-512, salted) Encrypted HEX: 02997c9c6eb26af1a335ed8c11d53df3bf127086ecbba02fb73391bcf385bd2c
AES 256 CBC (SHA-512, salted) Decrypted: Really secret message!
AES 128 CBC (WITH IV) Encrypted HEX: f9fa30df0325a7680327842c6a232e7838f7149d80cb8a669cf503a45afc2fa5
AES 128 CBC (WITH IV) Decrypted: Really secret message!
```
