### ISSUE TITLE
AES-256 CTR not declared

### ISSUE THREAD

**Issue by c64bob** [openresty/lua-resty-string#55]
I need to use AES 256 CTR, however it isn't declared in aes.lua:

> runtime error: /usr/local/openresty/lualib/resty/aes.lua:120: missing declaration for symbol 'EVP_aes_256_ctr'

Could you add that please?

**Comment by agentzh** [comment]
@c64bob No, we no longer want to add such crypto features to this library. Please use some other `lua-resty-*` library instead.

**Comment by c64bob** [comment]
Could I ask you to reconsider? You have declared every other crypto feature, only ctr for 256 bit is missing. All it takes is just one more line. I'll happily submit a PR. Please?
