### ISSUE TITLE
How to build cipher of AES/ECB/NoPadding by resty.aes module?

### ISSUE THREAD

**Issue by xiongmaodada** [openresty/lua-resty-string#59]
The default padding for aes is PKCS7, so how to set  NoPadding for the padding of  aes by `resty.aes` module?

**Comment by Prasanna-sr** [comment]
any updates on this ?

**Comment by hunterli** [comment]
=== TEST 1: AES/ECB/NoPadding
--- http_config eval: $::HttpConfig
--- config
    location = /t {
        content_by_lua_block {
            local b64 = require("ngx.base64")
            local aes = require "resty.aes"
            local function set_padding(aes, pad)
                local ffi = require "ffi"
                local C = ffi.C
                ffi.cdef[[
                    typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
                
                    int EVP_CIPHER_CTX_set_padding(EVP_CIPHER_CTX *ctx, int pad);
                ]]
                local encrypt_ctx, decrypt_ctx = aes._encrypt_ctx, aes._decrypt_ctx

                if encrypt_ctx == nil or decrypt_ctx == nil then
                    return nil, "the aes instance doesn't existed"
                end

                -- @link https://github.com/openssl/openssl/blob/master/crypto/evp/evp_enc.c#L402-L410
                C.EVP_CIPHER_CTX_set_padding(encrypt_ctx, pad)

                -- @link https://github.com/openssl/openssl/blob/master/crypto/evp/evp_enc.c#L515-L523
                C.EVP_CIPHER_CTX_set_padding(decrypt_ctx, pad)
            end

            local str = require "resty.string"
            local encdec, err = aes:new('NDAzMzY3LDE0MjI4', nil, aes.cipher(128, "ecb"), {['iv'] = 'ivforecbisnotuse'})
            if not encdec then
                ngx.log(ngx.ERR, 'encdec is nil', err)
            end
            set_padding(encdec, 0)
            ngx.say(b64.encode_base64url(encdec:encrypt("2301            ")))
            ngx.say(encdec:decrypt(b64.decode_base64url('O-0mVdLfTGAnt3TClMitSg==')))
        }
    }
--- request
GET /t
--- response_body
O-0mVdLfTGAnt3TClMitSg
2301            
--- error_code: 200

**Comment by xiongmaodada** [comment]
@hunterli thanks for your reply.

**Comment by agentzh** [comment]
BTW, never use `ffi.cdef()` (and other similar API calls) in request handler, since repeatedly calling it upon every request is wasteful and will also leak memory. Use it on the top-level of a custom Lua module and make sure lua_code_cache is off.

**Comment by shuxiao9058** [comment]
> BTW, never use `ffi.cdef()` (and other similar API calls) in request handler, since repeatedly calling it upon every request is wasteful and will also leak memory. Use it on the top-level of a custom Lua module and make sure lua_code_cache is off.

hi, @agentzh , why make sure `lua_code_cache ` off ?
